# -*- coding: utf-8 -*-
{
    'name': 'API Request Tester',
    'version': '19.0.2.0.0',
    'category': 'Tools',
    'summary': 'Postman-like interface to test API requests from server IP',
    'description': """
        Full-featured Postman clone built with OWL components inside Odoo.
        Features: cURL import, folder hierarchy, auth types (Bearer, Basic, API Key),
        body types (JSON, Raw, Form Data, URL Encoded, GraphQL),
        environment variables, request history, collections, and assertions.
    """,
    'author': 'Odiware Technologies',
    'website': 'https://www.odiware.com',
    'depends': ['base', 'web'],
    'data': [
        'security/api_tester_security.xml',
        'security/ir.model.access.csv',
        'data/api_tester_cron.xml',
        'views/api_request_views.xml',
        'views/api_saved_request_views.xml',
        'views/api_history_views.xml',
        'views/api_collection_views.xml',
        'views/api_folder_views.xml',
        'views/api_environment_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'api_request_tester/static/src/scss/api_tester.scss',
            'api_request_tester/static/src/js/utils/curl_parser.js',
            'api_request_tester/static/src/js/key_value_editor.js',
            'api_request_tester/static/src/js/body_editor.js',
            'api_request_tester/static/src/js/auth_editor.js',
            'api_request_tester/static/src/js/collection_tree_item.js',
            'api_request_tester/static/src/js/sidebar_panel.js',
            'api_request_tester/static/src/js/request_tabs.js',
            'api_request_tester/static/src/js/response_panel.js',
            'api_request_tester/static/src/js/api_tester_action.js',
            'api_request_tester/static/src/js/api_guide_action.js',
            'api_request_tester/static/src/xml/key_value_editor.xml',
            'api_request_tester/static/src/xml/body_editor.xml',
            'api_request_tester/static/src/xml/auth_editor.xml',
            'api_request_tester/static/src/xml/collection_tree_item.xml',
            'api_request_tester/static/src/xml/sidebar_panel.xml',
            'api_request_tester/static/src/xml/request_tabs.xml',
            'api_request_tester/static/src/xml/response_panel.xml',
            'api_request_tester/static/src/xml/api_tester_action.xml',
            'api_request_tester/static/src/xml/api_guide_action.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
